// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: snake.proto

package snake

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Move_Direction int32

const (
	Move_LEFT  Move_Direction = 0
	Move_RIGHT Move_Direction = 1
	Move_UP    Move_Direction = 2
	Move_DOWN  Move_Direction = 3
)

// Enum value maps for Move_Direction.
var (
	Move_Direction_name = map[int32]string{
		0: "LEFT",
		1: "RIGHT",
		2: "UP",
		3: "DOWN",
	}
	Move_Direction_value = map[string]int32{
		"LEFT":  0,
		"RIGHT": 1,
		"UP":    2,
		"DOWN":  3,
	}
)

func (x Move_Direction) Enum() *Move_Direction {
	p := new(Move_Direction)
	*p = x
	return p
}

func (x Move_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Move_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_snake_proto_enumTypes[0].Descriptor()
}

func (Move_Direction) Type() protoreflect.EnumType {
	return &file_snake_proto_enumTypes[0]
}

func (x Move_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Move_Direction.Descriptor instead.
func (Move_Direction) EnumDescriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{1, 0}
}

// Points are represent positions on the board.
type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dir       Move_Direction `protobuf:"varint,2,opt,name=dir,proto3,enum=snake.Move_Direction" json:"dir,omitempty"`
	PosAtMove *Point         `protobuf:"bytes,3,opt,name=posAtMove,proto3" json:"posAtMove,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Move) GetDir() Move_Direction {
	if x != nil {
		return x.Dir
	}
	return Move_LEFT
}

func (x *Move) GetPosAtMove() *Point {
	if x != nil {
		return x.PosAtMove
	}
	return nil
}

type PlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId   string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{2}
}

func (x *PlayRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type GameSetup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId      string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	BoardWidth  int32  `protobuf:"varint,2,opt,name=boardWidth,proto3" json:"boardWidth,omitempty"`
	BoardHeight int32  `protobuf:"varint,3,opt,name=boardHeight,proto3" json:"boardHeight,omitempty"`
}

func (x *GameSetup) Reset() {
	*x = GameSetup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSetup) ProtoMessage() {}

func (x *GameSetup) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSetup.ProtoReflect.Descriptor instead.
func (*GameSetup) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{3}
}

func (x *GameSetup) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameSetup) GetBoardWidth() int32 {
	if x != nil {
		return x.BoardWidth
	}
	return 0
}

func (x *GameSetup) GetBoardHeight() int32 {
	if x != nil {
		return x.BoardHeight
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GameUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player1Points   int32  `protobuf:"varint,1,opt,name=player1Points,proto3" json:"player1Points,omitempty"`
	Player2Points   int32  `protobuf:"varint,2,opt,name=player2Points,proto3" json:"player2Points,omitempty"`
	Bait            *Point `protobuf:"bytes,3,opt,name=bait,proto3" json:"bait,omitempty"`
	Player2LastMove *Move  `protobuf:"bytes,4,opt,name=player2LastMove,proto3" json:"player2LastMove,omitempty"`
}

func (x *GameUpdate) Reset() {
	*x = GameUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdate) ProtoMessage() {}

func (x *GameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdate.ProtoReflect.Descriptor instead.
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{5}
}

func (x *GameUpdate) GetPlayer1Points() int32 {
	if x != nil {
		return x.Player1Points
	}
	return 0
}

func (x *GameUpdate) GetPlayer2Points() int32 {
	if x != nil {
		return x.Player2Points
	}
	return 0
}

func (x *GameUpdate) GetBait() *Point {
	if x != nil {
		return x.Bait
	}
	return nil
}

func (x *GameUpdate) GetPlayer2LastMove() *Move {
	if x != nil {
		return x.Player2LastMove
	}
	return nil
}

type GameSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player1Points int32 `protobuf:"varint,1,opt,name=player1Points,proto3" json:"player1Points,omitempty"`
	Player2Points int32 `protobuf:"varint,2,opt,name=player2Points,proto3" json:"player2Points,omitempty"`
	GameEnded     bool  `protobuf:"varint,3,opt,name=gameEnded,proto3" json:"gameEnded,omitempty"`
	ElapsedTime   int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
}

func (x *GameSummary) Reset() {
	*x = GameSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snake_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSummary) ProtoMessage() {}

func (x *GameSummary) ProtoReflect() protoreflect.Message {
	mi := &file_snake_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSummary.ProtoReflect.Descriptor instead.
func (*GameSummary) Descriptor() ([]byte, []int) {
	return file_snake_proto_rawDescGZIP(), []int{6}
}

func (x *GameSummary) GetPlayer1Points() int32 {
	if x != nil {
		return x.Player1Points
	}
	return 0
}

func (x *GameSummary) GetPlayer2Points() int32 {
	if x != nil {
		return x.Player2Points
	}
	return 0
}

func (x *GameSummary) GetGameEnded() bool {
	if x != nil {
		return x.GameEnded
	}
	return false
}

func (x *GameSummary) GetElapsedTime() int32 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

var File_snake_proto protoreflect.FileDescriptor

var file_snake_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x9f, 0x01, 0x0a, 0x04, 0x4d, 0x6f,
	0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x2a, 0x0a, 0x09, 0x70,
	0x6f, 0x73, 0x41, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x70, 0x6f,
	0x73, 0x41, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x22, 0x32, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x22, 0x49, 0x0a, 0x0b, 0x50,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x27, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x31, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x61, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x62,
	0x61, 0x69, 0x74, 0x12, 0x35, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x4c, 0x61,
	0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x32, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x0b, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x31, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e,
	0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x45,
	0x6e, 0x64, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x6c, 0x61, 0x70,
	0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xaa, 0x01, 0x0a, 0x05, 0x53, 0x6e, 0x61, 0x6b,
	0x65, 0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x12, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x73, 0x6e, 0x61,
	0x6b, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79, 0x12,
	0x0b, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x1a, 0x12, 0x2e, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x42, 0x39, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75,
	0x69, 0x64, 0x65, 0x42, 0x0f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x3b, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snake_proto_rawDescOnce sync.Once
	file_snake_proto_rawDescData = file_snake_proto_rawDesc
)

func file_snake_proto_rawDescGZIP() []byte {
	file_snake_proto_rawDescOnce.Do(func() {
		file_snake_proto_rawDescData = protoimpl.X.CompressGZIP(file_snake_proto_rawDescData)
	})
	return file_snake_proto_rawDescData
}

var file_snake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_snake_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_snake_proto_goTypes = []interface{}{
	(Move_Direction)(0),   // 0: snake.Move.Direction
	(*Point)(nil),         // 1: snake.Point
	(*Move)(nil),          // 2: snake.Move
	(*PlayRequest)(nil),   // 3: snake.PlayRequest
	(*GameSetup)(nil),     // 4: snake.GameSetup
	(*UpdateRequest)(nil), // 5: snake.UpdateRequest
	(*GameUpdate)(nil),    // 6: snake.GameUpdate
	(*GameSummary)(nil),   // 7: snake.GameSummary
}
var file_snake_proto_depIdxs = []int32{
	0, // 0: snake.Move.dir:type_name -> snake.Move.Direction
	1, // 1: snake.Move.posAtMove:type_name -> snake.Point
	1, // 2: snake.GameUpdate.bait:type_name -> snake.Point
	2, // 3: snake.GameUpdate.player2LastMove:type_name -> snake.Move
	3, // 4: snake.Snake.GetGameRoom:input_type -> snake.PlayRequest
	5, // 5: snake.Snake.GetGameUpdates:input_type -> snake.UpdateRequest
	2, // 6: snake.Snake.Play:input_type -> snake.Move
	4, // 7: snake.Snake.GetGameRoom:output_type -> snake.GameSetup
	6, // 8: snake.Snake.GetGameUpdates:output_type -> snake.GameUpdate
	7, // 9: snake.Snake.Play:output_type -> snake.GameSummary
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_snake_proto_init() }
func file_snake_proto_init() {
	if File_snake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSetup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snake_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snake_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snake_proto_goTypes,
		DependencyIndexes: file_snake_proto_depIdxs,
		EnumInfos:         file_snake_proto_enumTypes,
		MessageInfos:      file_snake_proto_msgTypes,
	}.Build()
	File_snake_proto = out.File
	file_snake_proto_rawDesc = nil
	file_snake_proto_goTypes = nil
	file_snake_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SnakeClient is the client API for Snake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnakeClient interface {
	// A Simple RPC
	//
	// Requests access to a game room to play
	//
	// A game setup including game room ID, board size and
	// the other player's info
	GetGameRoom(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*GameSetup, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the updated position of the other player's snake, points
	// and bait position. Stream ends when there's a winner.
	GetGameUpdates(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (Snake_GetGameUpdatesClient, error)
	// A client-to-server streaming RPC.
	//
	// Sends my snake movements to the server. When I stop
	// sending movements I get a summary of the game.
	Play(ctx context.Context, opts ...grpc.CallOption) (Snake_PlayClient, error)
}

type snakeClient struct {
	cc grpc.ClientConnInterface
}

func NewSnakeClient(cc grpc.ClientConnInterface) SnakeClient {
	return &snakeClient{cc}
}

func (c *snakeClient) GetGameRoom(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*GameSetup, error) {
	out := new(GameSetup)
	err := c.cc.Invoke(ctx, "/snake.Snake/GetGameRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snakeClient) GetGameUpdates(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (Snake_GetGameUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Snake_serviceDesc.Streams[0], "/snake.Snake/GetGameUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &snakeGetGameUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Snake_GetGameUpdatesClient interface {
	Recv() (*GameUpdate, error)
	grpc.ClientStream
}

type snakeGetGameUpdatesClient struct {
	grpc.ClientStream
}

func (x *snakeGetGameUpdatesClient) Recv() (*GameUpdate, error) {
	m := new(GameUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snakeClient) Play(ctx context.Context, opts ...grpc.CallOption) (Snake_PlayClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Snake_serviceDesc.Streams[1], "/snake.Snake/Play", opts...)
	if err != nil {
		return nil, err
	}
	x := &snakePlayClient{stream}
	return x, nil
}

type Snake_PlayClient interface {
	Send(*Move) error
	CloseAndRecv() (*GameSummary, error)
	grpc.ClientStream
}

type snakePlayClient struct {
	grpc.ClientStream
}

func (x *snakePlayClient) Send(m *Move) error {
	return x.ClientStream.SendMsg(m)
}

func (x *snakePlayClient) CloseAndRecv() (*GameSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GameSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SnakeServer is the server API for Snake service.
type SnakeServer interface {
	// A Simple RPC
	//
	// Requests access to a game room to play
	//
	// A game setup including game room ID, board size and
	// the other player's info
	GetGameRoom(context.Context, *PlayRequest) (*GameSetup, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the updated position of the other player's snake, points
	// and bait position. Stream ends when there's a winner.
	GetGameUpdates(*UpdateRequest, Snake_GetGameUpdatesServer) error
	// A client-to-server streaming RPC.
	//
	// Sends my snake movements to the server. When I stop
	// sending movements I get a summary of the game.
	Play(Snake_PlayServer) error
}

// UnimplementedSnakeServer can be embedded to have forward compatible implementations.
type UnimplementedSnakeServer struct {
}

func (*UnimplementedSnakeServer) GetGameRoom(context.Context, *PlayRequest) (*GameSetup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameRoom not implemented")
}
func (*UnimplementedSnakeServer) GetGameUpdates(*UpdateRequest, Snake_GetGameUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetGameUpdates not implemented")
}
func (*UnimplementedSnakeServer) Play(Snake_PlayServer) error {
	return status.Errorf(codes.Unimplemented, "method Play not implemented")
}

func RegisterSnakeServer(s *grpc.Server, srv SnakeServer) {
	s.RegisterService(&_Snake_serviceDesc, srv)
}

func _Snake_GetGameRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnakeServer).GetGameRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snake.Snake/GetGameRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnakeServer).GetGameRoom(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snake_GetGameUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnakeServer).GetGameUpdates(m, &snakeGetGameUpdatesServer{stream})
}

type Snake_GetGameUpdatesServer interface {
	Send(*GameUpdate) error
	grpc.ServerStream
}

type snakeGetGameUpdatesServer struct {
	grpc.ServerStream
}

func (x *snakeGetGameUpdatesServer) Send(m *GameUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Snake_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnakeServer).Play(&snakePlayServer{stream})
}

type Snake_PlayServer interface {
	SendAndClose(*GameSummary) error
	Recv() (*Move, error)
	grpc.ServerStream
}

type snakePlayServer struct {
	grpc.ServerStream
}

func (x *snakePlayServer) SendAndClose(m *GameSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *snakePlayServer) Recv() (*Move, error) {
	m := new(Move)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Snake_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snake.Snake",
	HandlerType: (*SnakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameRoom",
			Handler:    _Snake_GetGameRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetGameUpdates",
			Handler:       _Snake_GetGameUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Play",
			Handler:       _Snake_Play_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "snake.proto",
}
